version: "3"

services:
  mongodb:
    build: mongo
    container_name: soldout_mongodb
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: "soldout"
    volumes:
      - ./data/db:/data/db
      - ./data/backup:/data/backup
    restart: always

  server:
    container_name: soldout_server
    build: server
    environment:
      MONGO_URL: $MONGO_URL
      ADMIN_SECRET: $ADMIN_SECRET
    ports:
      - "4000:3000"
    restart: always
    depends_on:
      - mongodb
    command: "yarn start:forever"

  client:
    container_name: soldout_client
    build: client
    volumes:
      - ./client/build:/client/build
    command: "yarn build"
