version: "3"

services:
  mongodb:
    build: mongo
    container_name: music10_mongodb
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: "music10"
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./data/backup:/data/backup
    restart: always

  server:
    container_name: music10_server
    build: server
    ports:
      - "4000:3000"
    restart: always
    depends_on:
      - mongodb
    command: "yarn start:dev"

  client:
    container_name: music10_client
    build: client
    ports:
      - "3000:3000"
    volumes:
      - ./client/build:/client/build
    command: "yarn start"
