version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGODB_DATABASE=gts

  server:
    build: ./server
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongodb
    command: 'yarn start:prod'

  client:
    build:
      context: client
    volumes:
      - ./client/build:/client/build
    command: 'npm run build'
