version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGODB_DATABASE="gts-test"
    ports:
      - 27017:27017

  server:
    build: ./server
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./server/src:/server/src
    command: 'npm run start'

  client:
    build:
      context: client
    ports:
      - "3001:3001"
    volumes:
      - ./client/src:/client/src
    environment:
      - PORT=3001
    command: 'npm run start'
