version: "3"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="gts"
    ports:
      - 27017:27017
  nestjs:
    build: .
    ports:
      - "3000:3000"
    command: 'npm run start'
    volumes:
      - .:/src
